In [1]:
import numpy as np

Creating arrays

In [2]:
tmp = np.array([1, 2, 3, 4, 5], dtype=np.uint16)
tmp1 = np.zeros([5, 3])
tmp2 = np.ones([3,4])
tmp3 = np.random.randn(4, 2) # random normal distribution -> Mean 0, SD 1
tmp4 = np.random.randint(5,10, [3,4])
tmp5 = np.linspace(0, 10, 20) # lower bound, upper bound, no. of elements
tmp6 = np.arange(0, 10, 0.6) # lower bound, upper bound, spacing between elements
print(tmp6)

[0.  0.6 1.2 1.8 2.4 3.  3.6 4.2 4.8 5.4 6.  6.6 7.2 7.8 8.4 9.  9.6]


Array Operations

In [3]:
2* tmp
1/tmp

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [4]:
tmp[tmp>3]

array([4, 5], dtype=uint16)

Array Indexing/Slicing

In [5]:
a1 = np.array([2, 4, 6, 8, 10])
a1[1:4]

array([4, 6, 8])